#!/bin/bash

cat << EOF

# Create a new repository

touch README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin <URL>
git push -u origin master

# Push an existing repository from the command line

git remote add origin <URL>
git push -u origin master

EOF
